# action.yml
name: 'SFTP Deploy'
description: 'Deploy files to your server with SFTP and password authenticated SSH'
inputs:
  username:
    description: 'username'
    required: true
  server:
    description: 'your SSH server'
    required: true
  port:
    description: 'your SSH server port, defaults to 22'
    required: true
    default: "22"
  ssh_password:
    description: 'you SSH password'
    required: true
  local_path:
    description: 'will transfer all files from this path'
    required: true
    default: ./*
  remote_path:
    description: 'files will be transferred to this path'
    required: true
    default: /

  args:
    description: 'sftp args'
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.server }}
    - ${{ inputs.port }}
    - ${{ inputs.ssh_password }}
    - ${{ inputs.local_path }}
    - ${{ inputs.remote_path }}
    - ${{ inputs.args }}

branding:
  icon: 'upload-cloud'
  color: 'purple'
