# action.yml
name: 'SFTP Deploy'
description: 'Deploy file to your server use sftp & ssh private key'
inputs:
  username:
    description: 'username'
    required: true
   password:
     description: 'password'
     required: true
  server:  
    description: 'your sftp server'
    required: true
  port: 
    description: 'your sftp server port, default to 22'
    required: true
    default: "22"
  ssh_private_key:
    description: 'you can copy private_key from your *.pem file, keep format'
    required: true
  local_path:
    description: 'will put all file under this path'
    required: true
    default: ./*
  remote_path:
    description: 'files will copy to under remote_path'
    required: true
    default: /

  args:
    description: 'sftp args'
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.server }}
    - ${{ inputs.port }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.local_path }}
    - ${{ inputs.remote_path }}
    - ${{ inputs.args }}

branding:
  icon: 'upload-cloud'  
  color: 'purple'
